sudo: required
services:
  - docker

before_install:
  - docker build -t abdirisakarr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abdirisakarr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "react-docker"
  env: "React-docker-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-968573977664"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
